apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: mysql
    project: expense

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers:
        - name: mysql
          image: gowtham330/mysql:1.1.0

---

apiVersion: v1
kind: Service
metadata:
  name: mysql 
  namespace: expense 
spec:
  selector:
    app: mysql
    tier: mysql
    project: expense

  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    
            